"""renamed birthday column

Revision ID: 4f820e56b9fe
Revises: 791279dd0760
Create Date: 2024-12-18 15:49:31.797526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f820e56b9fe'
down_revision = '791279dd0760'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('birthD', sa.DateTime(), nullable=True))
    op.drop_column('students', 'date_of_birth')
    op.drop_column('students', 'birthday')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('birthday', sa.DATETIME(), nullable=True))
    op.add_column('students', sa.Column('date_of_birth', sa.DATETIME(), nullable=True))
    op.drop_column('students', 'birthD')
    # ### end Alembic commands ###
